### ISSUE TITLE
Export Error "dict object has no attribute x" 

### ISSUE THREAD

**Issue by MadMax1960** [Pherakki/BlenderToolsForGFS#125]
**Describe the bug**
I export and it gives me that error, it's a custom armature from pokemon BDSP, along with chopped up anims. 

**To Reproduce**
1. Open Blend
2. Export gmd with animations packed (or export gap) 

**Expected behavior**
It should export

**Files**
https://cdn.discordapp.com/attachments/831687902824103977/1156251973411147977/mudkip_5_phe.blend?ex=65144b10&is=6512f990&hm=d4372b6c65dfd7767d2ecbbc5af6cef15f974c5b3e9d586ff4304a79c6a48a80&

**Additional context**
Traceback (most recent call last):
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderToolsForGFS\src\BlenderIO\WarningSystem\Handler.py", line 15, in handled_execute
    return function(self, *args, **kwargs)
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderToolsForGFS\src\BlenderIO\Export\Operator.py", line 167, in export_file
    export_animations(gfs, selected_model, keep_unused_anims=False)
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderToolsForGFS\src\BlenderIO\Export\ExportAnimations.py", line 57, in export_animations
    if   action.GFSTOOLS_AnimationProperties.category == "NORMAL": export_animation(gfs, armature, gfs.add_animation(),       action, is_blend=False, keep_unused_anims=keep_unused_anims)
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderToolsForGFS\src\BlenderIO\Export\ExportAnimations.py", line 79, in export_animation
    node_transforms, root_transform = get_action_data(action, armature, is_blend)
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderToolsForGFS\src\BlenderIO\Export\ExportAnimations.py", line 291, in get_action_data
    rotations = {k: [q.x, q.y, q.z, q.w] for k, q in rotations.items()}
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderToolsForGFS\src\BlenderIO\Export\ExportAnimations.py", line 291, in <dictcomp>
    rotations = {k: [q.x, q.y, q.z, q.w] for k, q in rotations.items()}
AttributeError: 'dict' object has no attribute 'x'

**Comment by Pherakki** [comment]
Fixed on develop
