### ISSUE TITLE
Export issue 'list' object has no attribute 'add'

### ISSUE THREAD

**Issue by MadMax1960** [Pherakki/BlenderToolsForGFS#138]
**Describe the bug**
Export fails 

**To Reproduce**
1. Open Blend
2. Export

**Expected behavior**
It should export 

**Files**
(https://cdn.discordapp.com/attachments/1152787328532754472/1159175515689717820/weeeeeeeeeee.blend?ex=651eedd3&is=651d9c53&hm=0099d7e725b035849e0f8d1b3f02395102cc7836d252d7e2dbfaf0d58990aaa8&)

**Additional context**
Traceback (most recent call last):
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderToolsForGFS-develop\src\BlenderIO\WarningSystem\Handler.py", line 15, in handled_execute
    return function(self, *args, **kwargs)
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderToolsForGFS-develop\src\BlenderIO\Export\Operator.py", line 170, in export_file
    bpy_material_names = export_mesh_data(gfs, selected_model, bpy_to_gfs_nodes, bind_pose_matrices, errorlog, self.policies)
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderToolsForGFS-develop\src\BlenderIO\Export\ExportModel\Mesh.py", line 51, in export_mesh_data
    gfs_meshes.append(create_mesh(gfs, bpy_mesh_object, armature, node_id, material_names, material_index, errorlog, export_policies))
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderToolsForGFS-develop\src\BlenderIO\Export\ExportModel\Mesh.py", line 232, in create_mesh
    mesh_buffers = extract_vertices(bpy_mesh_object, bone_names, errorlog, export_policies)
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderToolsForGFS-develop\src\BlenderIO\Export\ExportModel\Vertices.py", line 73, in extract_vertices
    mesh_buffers = bpy_mesh_to_VBO_IBO(bpy_mesh, vertex_getter, loop_data, construct_vertex)
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderToolsForGFS-develop\src\BlenderIO\modelUtilsTest\Mesh\Export\ExtractMeshBuffers.py", line 41, in bpy_mesh_to_VBO_IBO
    vertex_data = get_vertex_data(vert_idx, vertex)
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderToolsForGFS-develop\src\BlenderIO\Export\ExportModel\Vertices.py", line 282, in __call__
    self.missing_bone_names.add(bone_name)
AttributeError: 'list' object has no attribute 'add'

**Comment by Pherakki** [comment]
Fixed in f62921b41ef6e5b92683c19d9ae1812ee6213a1d
