### ISSUE TITLE
'NlaStrip' object has no attribute 'frame_start_ui'

### ISSUE THREAD

**Issue by BobbyTheCatfish** [Pherakki/BlenderToolsForGFS#153]
Tried importing EMT0001.gap, hitting the activate gap button, (got the stacktrace error below), and importing again which gave the `'NlaStrip' object has no attribute 'frame_start_ui'` error. Sorry in advance about how poorly structured this is going to be

Stacktrace:
Python: Traceback (most recent call last):
  File "C:\Users\REDACTED\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderToolsForGFS\src\BlenderIO\UI\Model\AnimationsSubPanel\GAPPanel.py", line 38, in execute
    selected_gap.add_to_nla(bpy_armature_object)
  File "C:\Users\REDACTED\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderToolsForGFS\src\BlenderIO\Properties\AnimationPack.py", line 674, in add_to_nla
    track = prop_anim.node_animation.to_nla_track(ad, self.name, BLEND_ANIM_TYPE, prop_anim.name)
  File "C:\Users\REDACTED\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderToolsForGFS\src\BlenderIO\Properties\AnimationPack.py", line 99, in to_nla_track
    prop_strip.to_nla_strip(track)
  File "C:\Users\REDACTED\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderToolsForGFS\src\BlenderIO\Properties\AnimationPack.py", line 69, in to_nla_strip
    nla_strip.frame_start_ui     = self.frame_start_ui
AttributeError: 'NlaStrip' object has no attribute 'frame_start_ui'

This stacktrace got sent after trying to activate the imported gap, then `'NlaStrip' object has no attribute 'frame_start_ui'` popped up as an error box when i tried to import it again.

**Comment by Pherakki** [comment]
Thanks for the error report. I will investigate and put the fix in a bugfix update alongside some other small fixes this week, assuming no big problems.

**Comment by Pherakki** [comment]
Fixed in 0d0d56a769a1980903cabf27b25615538e6cbfd0, included in public release [0.2.1](https://github.com/Pherakki/BlenderToolsForGFS/releases/tag/v0.2.1).
