### ISSUE TITLE
Metaphor support

### ISSUE THREAD

**Issue by Andree12** [Pherakki/BlenderToolsForGFS#159]
**Describe the bug**
Metaphor uses the same engine as Persona 5 Royal, when importing a .gfs file from Metaphor, a popup will show up due to the header being different, replacing the first instance of '0SFG' with 'GFS0' with hex editor and importing the modified .gfs file will result in a error due to its unrecognized container type.

**To Reproduce**
1. Open a .gfs file from Megaphor with a hex editor 
2. Replace the first instance of 0SFG with GFS0 and then save it in somewhere
3. Go to blender
4. Click on file 
5. Click 'import'
6. Scroll down to 'GFS' and click on 'GFS model'
7. Import the modified .gfs file
8. An error like below will pop up in the console

```
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderToolsForGFS\src\BlenderIO\modelUtilsTest\Misc\Errorlog\Handler.py", line 10, in handled_execute
    return function(self, *args, **kwargs)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderToolsForGFS\src\BlenderIO\Import\Operator.py", line 135, in import_file
    gfs = GFSInterface.from_bytes(raw_gfs, warnings=warnings)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderToolsForGFS\src\FileFormats\GFS\Interface.py", line 86, in from_bytes
    binary.unpack(bytes_, warnings=warnings)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderToolsForGFS\src\serialization\Serializable.py", line 33, in unpack
    rw.rw_obj(self, *args, **kwargs)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderToolsForGFS\src\serialization\BinaryTargets.py", line 71, in rw_obj
    obj.read_write(self, *args, **kwargs)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderToolsForGFS\src\FileFormats\GFS\Binary.py", line 41, in read_write
    rw.rw_obj(ctr)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderToolsForGFS\src\serialization\BinaryTargets.py", line 71, in rw_obj
    obj.read_write(self, *args, **kwargs)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderToolsForGFS\src\FileFormats\GFS\SubComponents\GFS0ContainerBinary.py", line 62, in read_write
    raise NotImplementedError(f"Unrecognised GFS Container Type: '{safe_format(self.type, hex32_format)}'")
NotImplementedError: Unrecognised GFS Container Type: '0x08000000'
```

**Expected behavior**
It was supposed to import a model from Metaphor: ReFantazio - Prologue Demo.

**Files**
Since this was taken from the free PC demo version of the game, I've extracted the original c_0001_001_B.gfs file from its base.cpk file and put into a zip file which it can be downloaded on the link below.
[c_0001_001_B.zip](https://github.com/user-attachments/files/17154601/c_0001_001_B.zip)

**Comment by Pherakki** [comment]
Relabelled this to a feature request since supporting file format changes is a new feature.
Might take me some time but I'm working on it where and when I can.

**Comment by sodamouse** [comment]
+1 to this feature request

**Comment by Pherakki** [comment]
[New release has basic Metaphor support](https://github.com/Pherakki/BlenderToolsForGFS/releases/tag/v0.3)
