### ISSUE TITLE
Attribute Error: 'Bone' object has no attribute 'layers'

### ISSUE THREAD

**Issue by TheOneRichardAllan** [Pherakki/BlenderToolsForGFS#161]
**Describe the bug**
When I put a model into Blender it just puts the skeleton

**To Reproduce**
Go to File>Import>GFS Model>[MODEL]

**Expected behavior**
I expected the model to load in

**Files**
File inserted was C0001_004_00.GMD (Joker's Winter Casual Outfit) from Persona 5 Royal (happens with any model really)

**Console**

Traceback (most recent call last):
  File "C:\Users\Richard\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\BlenderToolsForGFS\src\BlenderIO\WarningSystem\Handler.py", line 15, in handled_execute
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Richard\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\BlenderToolsForGFS\src\BlenderIO\Import\Operator.py", line 105, in import_file
    armature, gfs_to_bpy_bone_map, mesh_node_map = import_model(gfs, os.path.split(filepath)[1].split('.')[0], materials, errorlog, self.merge_vertices, self.bone_pose, filepath)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Richard\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\BlenderToolsForGFS\src\BlenderIO\Import\ImportModel.py", line 213, in import_model
    bpy_bone.layers[0] = True
    ^^^^^^^^^^^^^^^
AttributeError: 'Bone' object has no attribute 'layers'

**Comment by Pherakki** [comment]
This should be fixed by the latest release. Thanks for reporting the incompatibility with version 4.X.

**Comment by GirlyCrystal** [comment]
> This should be fixed by the latest release. Thanks for reporting the incompatibility with version 4.X.

Hey, I'm having this same issue currently, did u fix it? its probs me being dumb tbh
