### ISSUE TITLE
Animation Import Error P5R

### ISSUE THREAD

**Issue by ErcarA** [Pherakki/BlenderToolsForGFS#162]
**Describe the bug**
When importing Joker's main battle gap BB0001_051 the animations don't import and I'm met with an error

**To Reproduce**
1. Go to File>Import>GFS Model>[GAP Animations]
2. BB0001_051.GAP

**Console**
File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderToolsForGFS\src\FileFormats\GFS\SubComponents\Animations\NodeAnimation.py", line 94, in <dictcomp>
    anim.rotations = {f: kf.rotation for f, kf in zip(track_binary.frames, track_binary.values)}
AttributeError: 'NodeTHalf' object has no attribute 'rotation'

**Notes** 
This doesn't happen with all GAPs but I do not know if any other ones trigger this error

**Comment by Pherakki** [comment]
Fixed in 4dcacf24335d0c6291506e5f71a3004b99835709 and implemented in latest release. Thanks for the report!

**Comment by Fayande** [comment]
Still running into this issue even after the latest release. Not sure if fix didn't work or if I somehow messed up updating on my end? but the version number in Blender matches the latest

Console says this if it helps:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderToolsForGFS\src\BlenderIO\modelUtilsTest\Misc\Errorlog\Handler.py", line 10, in handled_execute
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderToolsForGFS\src\BlenderIO\Import\Operator.py", line 269, in import_file
    gfs = GFSInterface.from_file(filepath, warnings=warnings)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderToolsForGFS\src\FileFormats\GFS\Interface.py", line 80, in from_file
    return cls.from_binary(binary, duplicate_data=False, warnings=warnings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderToolsForGFS\src\FileFormats\GFS\Interface.py", line 155, in from_binary
    instance.animations = [AnimationInterface.from_binary(anim) for anim in ctr.data.animations]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderToolsForGFS\src\FileFormats\GFS\Interface.py", line 155, in <listcomp>
    instance.animations = [AnimationInterface.from_binary(anim) for anim in ctr.data.animations]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderToolsForGFS\src\FileFormats\GFS\SubComponents\Animations\Interface.py", line 133, in from_binary
    instance.node_animations.append    (NodeAnimation.from_controller(controller_binary))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderToolsForGFS\src\FileFormats\GFS\SubComponents\Animations\NodeAnimation.py", line 94, in from_controller
    anim.positions = {f: kf.position for f, kf in zip(track_binary.frames, track_binary.values)}
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderToolsForGFS\src\FileFormats\GFS\SubComponents\Animations\NodeAnimation.py", line 94, in <dictcomp>
    anim.positions = {f: kf.position for f, kf in zip(track_binary.frames, track_binary.values)}
                     ^^^^^^^^^^^
AttributeError: 'NodeTHalf' object has no attribute 'rotation'

**Comment by blxazedz** [comment]
having the same issue, even with latest release
