### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by MadMax1960** [Pherakki/BlenderToolsForGFS#81]
Stack Trace;

Traceback (most recent call last):
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlenderToolsForGFS\src\BlenderIO\WarningSystem\Handler.py", line 15, in handled_execute
    return function(self, *args, **kwargs)
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlenderToolsForGFS\src\BlenderIO\Import\Operator.py", line 67, in import_file
    gfs = GFSInterface.from_file(filepath)
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlenderToolsForGFS\src\FileFormats\GFS\Interface.py", line 78, in from_file
    return cls.from_binary(binary, duplicate_data=False)
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlenderToolsForGFS\src\FileFormats\GFS\Interface.py", line 98, in from_binary
    instance.flag_3 = ModelInterface.from_binary(ctr.data, duplicate_data)
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlenderToolsForGFS\src\FileFormats\GFS\SubComponents\Model\Interface.py", line 49, in from_binary
    v.indices = [binary.skinning_data.matrix_palette[idx] for idx in v.indices[::-1]]
  File "C:\Users\maxgo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlenderToolsForGFS\src\FileFormats\GFS\SubComponents\Model\Interface.py", line 49, in <listcomp>
    v.indices = [binary.skinning_data.matrix_palette[idx] for idx in v.indices[::-1]]
IndexError: array index out of range

File: https://cdn.discordapp.com/attachments/831687902824103977/1085162049652400168/c0006_171_00.GMD

**Comment by Pherakki** [comment]
Fixed in a32c0773053d6dc3d668438d826ebaf433e11296 and debug messages added in 0dd20e6d1ca77be6572d8b67ae6bb6132304c37a.
